name: Delete Workflow
on: 
  workflow_dispatch:

jobs:
  clean:
    name: Delete
    runs-on: ubuntu-latest
    steps:
      - name: clean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /pub/roshan98
            unalias rm
            rm -rf cmsc389T-web-template
